cargo-features = ["edition2024"]
[package]
name = "week35"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib","lib"]
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))', 'cfg(feature, values("custom-heap", "custom-panic"))'] }

[dependencies]
borsh = { version = "1.5.7", features = ["derive"] }
borsh-derive = "1.6.0"
solana-program = "3.0.0"

[dev-dependencies]
litesvm = "0.8.2"
solana-sdk = "3.0.0"
solana-system-interface = { version = "3.0.0", features = ["bincode"] }

